django:
  build: .
  command: python /app/manage.py runserver_plus 0.0.0.0:8000
  volumes:
    - .:/app
  ports:
    - "8000:8000"
  environment:
    - DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test
